// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { woocommerceBlock } from '.'
import { auth } from './auth'

export const woocommerceBlockSchema = parseBlockSchema(woocommerceBlock)
export const woocommerceCredentialsSchema = parseBlockCredentials(
  woocommerceBlock.id,
  auth.schema
)
